#makefile

test:
	gcc test.c -o test
	
test1:
	gcc test1.c -o test
	
test2:
	gcc test2.c -o test

test3:
	gcc test3.c -o test
	
tcp:
	gcc tcp_.c -o test
	
select:
	gcc select.c -o select
	
cliente:
	gcc client-inet-stream.c -o client
	
server:
	gcc udpserver.c -o server

clean:
	rm -f *.o *.~ test server client *.gch
